spring.application.name=crypto-tracker

# MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/crypto_tracker_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.url=jdbc:mariadb://localhost:3306/crypto_tracker_db
spring.flyway.user=user
spring.flyway.password=password
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# Mailer
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Security
application.security.jwt.secret-key=${JWT_SECRET_KEY}

# Client
application.coingecko.api-key=${CRYPTO_API_KEY}
application.coingecko.base-url=${COIN_BASE_URL}
